"use client";

import Link from "next/link";
import { Activity, Database, FileText, GitBranch, PlugZap } from "lucide-react";
import type { DataSourceDetail } from "@/lib/api-contract";
import { mapDataSourceDetail, NOT_AVAILABLE } from "@/lib/core-resource-adapters";
import { useApiQuery } from "@/lib/use-api-query";
import { Breadcrumbs, Button, Card, EmptyState, ErrorState, KeyValueGrid, OperationalStatus, PageHeader, Skeleton, StatusBadge } from "@/components/ui";

export function DataSourceDetailPage({ sourceKey }: { sourceKey: string }) {
    const request = useApiQuery<DataSourceDetail>(`/api/v1/data-sources/${encodeURIComponent(sourceKey)}`);
    if (request.loading && !request.data) return <DataSourceDetailSkeleton />;
    if (request.error) return <><Breadcrumbs items={[{ label: "Data Sources", href: "/data-sources" }, { label: sourceKey }]} /><ErrorState title={request.error.kind === "not_found" ? "Data source not found" : request.error.kind === "permission" ? "Permission denied" : "Data source couldn't be loaded"} description={request.error.message} actionLabel={request.error.retryable ? "Try Again" : undefined} onRetry={request.error.retryable ? request.retry : undefined} technicalDetails={[{label:"Platform Code",value:request.error.code}]} /></>;
    if (!request.data) return null;
    const source = mapDataSourceDetail(request.data);
    return <div className="animate-enter"><Breadcrumbs items={[{ label: "Data Sources", href: "/data-sources" }, { label: source.name }]} /><PageHeader title={source.name} description={source.description === NOT_AVAILABLE ? "Source description not available." : source.description} eyebrow={<><Database className="h-3 w-3" /> {source.type}<span className="text-zinc-300">·</span>{source.environment}<StatusBadge status={source.status} /></>} action={<div className="flex flex-wrap gap-2"><Link href={`/validation?source=${encodeURIComponent(source.id)}`}><Button>View Validation</Button></Link><Link href={`/logs?scope=source&source=${encodeURIComponent(source.id)}`}><Button><FileText className="h-3.5 w-3.5" /> View Logs</Button></Link><Button disabled title="Connection testing is not exposed by the Round 1 API"><PlugZap className="h-3.5 w-3.5" /> Test Connection</Button></div>} />
        <div className="grid gap-7 xl:grid-cols-2"><Card title="Operational Health" description="Latest authoritative source state."><div className="p-4"><dl className="mb-4 grid grid-cols-2 gap-3 rounded-lg bg-zinc-50 p-3 text-xs"><div><dt className="text-zinc-500">Source Status</dt><dd className="mt-1"><StatusBadge status={source.status} /></dd></div><div><dt className="text-zinc-500">Last observed</dt><dd className="mt-1 font-medium">{source.health.lastChecked}</dd></div><div><dt className="text-zinc-500">Response time</dt><dd className="mt-1 font-medium">{source.health.latency}</dd></div><div><dt className="text-zinc-500">Active alerts</dt><dd className="mt-1 font-medium">{request.data.active_alert_count}</dd></div></dl><OperationalStatus result={source.health} /></div></Card><Card title="Configuration Summary" description="Only persisted, non-sensitive source metadata is shown."><KeyValueGrid items={source.configuration} /></Card></div>
        <div className="mt-7"><Card title="Connected Pipelines" description={`${source.pipelines} connected ${source.pipelines === 1 ? "pipeline" : "pipelines"}.`}>{source.connectedPipelines.length ? <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="border-b bg-zinc-50 text-[10px] uppercase tracking-wider text-zinc-400"><th className="px-4 py-2.5">Pipeline</th><th className="px-3 py-2.5">Status</th><th className="px-3 py-2.5">Schedule</th><th className="px-3 py-2.5">Latest run</th></tr></thead><tbody>{source.connectedPipelines.map((pipeline) => <tr key={pipeline.id} className="border-b text-xs last:border-0"><td className="px-4 py-3"><Link href={`/pipelines/${pipeline.id}`} className="font-medium text-zinc-800 hover:text-indigo-700"><GitBranch className="mr-2 inline h-3.5 w-3.5" />{pipeline.name}</Link></td><td className="px-3 py-3"><StatusBadge status={pipeline.status} /></td><td className="px-3 py-3 text-zinc-500">{pipeline.schedule}</td><td className="px-3 py-3 text-zinc-500">{pipeline.lastRun}</td></tr>)}</tbody></table></div> : <div className="p-4"><EmptyState title="No connected pipelines" description="This source is not currently used by any pipelines." icon={<GitBranch className="h-4 w-4" />} /></div>}</Card></div>
        <div className="mt-7 grid gap-7 xl:grid-cols-2"><Card title="Validation Summary" description="Persisted validation results."><div className="grid grid-cols-3 gap-2 p-4">{[["Passed",source.validation.passed],["Warnings",source.validation.warnings],["Failed",source.validation.failed]].map(([label,value])=><div key={label} className="rounded-md bg-zinc-50 p-3"><p className="text-xl font-semibold">{value}</p><p className="text-[11px] text-zinc-500">{label}</p></div>)}<p className="col-span-3 text-xs text-zinc-500">Last evaluated: {source.validation.lastRun}</p></div></Card><Card title="Recent Technical Evidence" description="Authoritative events associated with this source.">{source.recentActivity.length ? <ol className="space-y-4 p-4">{source.recentActivity.map((item)=><li key={item.id} className="flex gap-3 text-xs"><Activity className="mt-0.5 h-4 w-4 text-zinc-400" /><div><p className="font-medium text-zinc-800">{item.title}</p><p className="mt-1 font-mono text-[10px] text-zinc-500">{item.detail}</p><time className="mt-1 block text-zinc-400">{item.time}</time></div></li>)}</ol> : <div className="p-4"><EmptyState title="No recent technical evidence" description="No technical events were returned for this source." icon={<Activity className="h-4 w-4" />} /></div>}</Card></div>
        <div className="mt-5 text-[11px] text-zinc-400">Owner: <strong>{source.owner}</strong> · Created: <strong>{source.createdAt}</strong> · Source key: <strong className="font-mono">{source.id}</strong></div></div>;
}

export function DataSourceDetailSkeleton() { return <div className="space-y-7"><Skeleton className="h-4 w-56" /><Skeleton className="h-20" /><div className="grid gap-7 xl:grid-cols-2"><Skeleton className="h-80" /><Skeleton className="h-80" /></div><Skeleton className="h-64" /></div>; }
