"use client";

import Link from "next/link";
import { Activity, Database, GitBranch, Timer } from "lucide-react";
import type { PipelineDetail } from "@/lib/api-contract";
import { mapPipelineDetail } from "@/lib/core-resource-adapters";
import { useApiQuery } from "@/lib/use-api-query";
import { Breadcrumbs, Button, Card, EmptyState, ErrorState, KeyValueGrid, MetricCard, OperationalStatus, PageHeader, Skeleton, StatusBadge } from "@/components/ui";

export function PipelineDetailPage({ pipelineKey }: { pipelineKey: string }) {
    const request = useApiQuery<PipelineDetail>(`/api/v1/pipelines/${encodeURIComponent(pipelineKey)}`);
    if(request.loading&&!request.data)return <PipelineDetailSkeleton/>;
    if(request.error)return <><Breadcrumbs items={[{label:"Pipelines",href:"/pipelines"},{label:pipelineKey}]}/><ErrorState title={request.error.kind==="not_found"?"Pipeline not found":request.error.kind==="permission"?"Permission denied":"Pipeline couldn't be loaded"} description={request.error.message} actionLabel={request.error.retryable?"Try Again":undefined} onRetry={request.error.retryable?request.retry:undefined} technicalDetails={[{label:"Platform Code",value:request.error.code}]}/></>;
    if(!request.data)return null;
    const pipeline=mapPipelineDetail(request.data);
    return <div className="animate-enter"><Breadcrumbs items={[{label:"Pipelines",href:"/pipelines"},{label:pipeline.name}]}/><PageHeader title={pipeline.name} description={`Pipeline key: ${pipeline.id}`} eyebrow={<><GitBranch className="h-3 w-3"/>{pipeline.environment}<StatusBadge status={pipeline.status}/></>} action={<div className="flex gap-2"><Link href={`/pipeline-runs?pipeline=${encodeURIComponent(pipeline.id)}`}><Button>View Runs</Button></Link><Button disabled title="Run mutations are outside the Round 1 integration scope">Run Pipeline</Button></div>}/>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Latest Run" value={pipeline.latestRun.value} detail={pipeline.latestRun.detail} icon={Activity}/><MetricCard label="Next Run" value={pipeline.nextRun} detail="Not supplied by this API" icon={Timer}/><MetricCard label="Duration" value={pipeline.duration} detail="Latest execution" icon={Timer}/><MetricCard label="Success Rate" value={pipeline.successRate} detail="Not supplied by this API" icon={Activity}/></div>
        <div className="mt-7"><Card title="Pipeline Flow" description="Canonical source and pipeline identity; destination is unavailable."><div className="flex flex-col items-center justify-center gap-3 p-5 md:flex-row"><Link href={`/data-sources/${pipeline.source.sourceId}`} className="min-w-[190px] rounded-lg border bg-white p-4 text-center shadow-card"><Database className="mx-auto h-4 w-4 text-zinc-400"/><p className="mt-2 text-sm font-medium">{pipeline.source.name}</p><p className="text-xs text-zinc-500">{pipeline.source.type} · {pipeline.source.status}</p></Link><span className="text-zinc-300">→</span><div className="min-w-[190px] rounded-lg border border-indigo-100 bg-indigo-50 p-4 text-center"><GitBranch className="mx-auto h-4 w-4 text-indigo-500"/><p className="mt-2 text-sm font-semibold">{pipeline.name}</p><p className="font-mono text-[10px] text-zinc-500">{pipeline.id}</p></div><span className="text-zinc-300">→</span><div className="min-w-[190px] rounded-lg border bg-white p-4 text-center"><Database className="mx-auto h-4 w-4 text-zinc-400"/><p className="mt-2 text-sm font-medium">{pipeline.destination.name}</p><p className="text-xs text-zinc-500">Destination</p></div></div></Card></div>
        <div className="mt-7 grid gap-7 xl:grid-cols-2"><Card title="Operational Status" description="Backend-authoritative health and current alert."><div className="p-4"><OperationalStatus result={pipeline.health}/><KeyValueGrid className="mt-4" items={pipeline.healthDetails}/></div></Card><Card title="Configuration" description="Only fields persisted by the API are shown."><KeyValueGrid items={pipeline.configuration}/></Card></div>
        <div className="mt-7"><Card title="Recent Runs" description="Canonical executions returned with this pipeline.">{pipeline.recentRuns.length?<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b bg-zinc-50 text-[10px] uppercase text-zinc-400"><th className="px-4 py-2.5">Run ID</th><th className="px-3 py-2.5">Status</th><th className="px-3 py-2.5">Started</th><th className="px-3 py-2.5">Duration</th><th className="px-3 py-2.5">Trigger</th></tr></thead><tbody>{pipeline.recentRuns.map((run)=><tr key={run.id} className="border-b text-xs last:border-0"><td className="px-4 py-3"><Link href={`/pipeline-runs/${run.id}`} className="font-mono font-medium text-indigo-700">{run.id}</Link></td><td className="px-3 py-3"><StatusBadge status={run.status}/></td><td className="px-3 py-3">{run.started}</td><td className="px-3 py-3">{run.duration}</td><td className="px-3 py-3">{run.trigger}</td></tr>)}</tbody></table></div>:<div className="p-4"><EmptyState title="No recent runs" description="No canonical executions were returned." icon={<Activity className="h-4 w-4"/>}/></div>}</Card></div>
        <div className="mt-7 grid gap-7 xl:grid-cols-2"><Card title="Validation Summary" description="Persisted validation totals."><div className="grid grid-cols-3 gap-2 p-4">{[["Checks",pipeline.validation.activeChecks],["Passing",pipeline.validation.passing],["Failed",pipeline.validation.failed]].map(([label,value])=><div key={label} className="rounded bg-zinc-50 p-3"><p className="text-lg font-semibold">{value}</p><p className="text-[11px] text-zinc-500">{label}</p></div>)}<p className="col-span-3 text-xs text-zinc-500">Last evaluated: {pipeline.validation.lastEvaluated}</p></div></Card><Card title="Active Alerts" description="Current operational alerts for this pipeline.">{request.data.active_alerts.length?<div className="space-y-3 p-4">{request.data.active_alerts.map((alert)=><div key={alert.alert_key} className="rounded border p-3 text-xs"><div className="flex justify-between"><strong>{alert.title}</strong><StatusBadge status={alert.status}/></div><p className="mt-2 text-zinc-600">{alert.message}</p><p className="mt-2 font-mono text-[10px]">{alert.platform_code}{alert.rule_code?` · Rule: ${alert.rule_code}`:alert.vendor_code?` · Vendor: ${alert.vendor_code}`:""}</p></div>)}</div>:<div className="p-4"><EmptyState title="No active alerts" description="No active alerts were returned." icon={<Activity className="h-4 w-4"/>}/></div>}</Card></div>
    </div>;
}
export function PipelineDetailSkeleton(){return <div className="space-y-7"><Skeleton className="h-20"/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:4}).map((_,i)=><Skeleton key={i} className="h-28"/>)}</div><Skeleton className="h-72"/><Skeleton className="h-64"/></div>}
