"use client";

import Link from "next/link";
import { Activity, CalendarClock, Clock3, Database, FileCheck2, FileText, GitBranch } from "lucide-react";
import type { PipelineRunDetail } from "@/lib/api-contract";
import { formatTimestamp } from "@/lib/api-adapters";
import { mapPipelineRunDetail, NOT_AVAILABLE } from "@/lib/core-resource-adapters";
import { useApiQuery } from "@/lib/use-api-query";
import { Breadcrumbs, Button, Card, EmptyState, ErrorState, MetricCard, OperationalStatus, PageHeader, Skeleton, StatusBadge, TechnicalDetails } from "@/components/ui";

export function PipelineRunDetailPage({runId}:{runId:string}){
 const request=useApiQuery<PipelineRunDetail>(`/api/v1/pipeline-runs/${encodeURIComponent(runId)}`);
 if(request.loading&&!request.data)return <PipelineRunDetailSkeleton/>;
 if(request.error)return <><Breadcrumbs items={[{label:"Pipeline Runs",href:"/pipeline-runs"},{label:runId}]}/><ErrorState title={request.error.kind==="not_found"?"Pipeline run not found":request.error.kind==="permission"?"Permission denied":"Pipeline run couldn't be loaded"} description={request.error.message} actionLabel={request.error.retryable?"Try Again":undefined} onRetry={request.error.retryable?request.retry:undefined} technicalDetails={[{label:"Platform Code",value:request.error.code}]}/></>;
 if(!request.data)return null;const run=mapPipelineRunDetail(request.data);const result={status:run.status==="Success"?"Success" as const:run.status==="Running"?"Running" as const:"Error" as const,platformCode:run.platformCode,...(run.vendorCode?{vendorCode:run.vendorCode}:{}),message:run.message,recommendedAction:run.recommendedAction};
 return <div className="animate-enter"><Breadcrumbs items={[{label:"Pipeline Runs",href:"/pipeline-runs"},{label:run.pipelineName,href:`/pipelines/${run.pipelineId}`},{label:run.id}]}/><PageHeader title={run.pipelineName} description={`Run ID: ${run.id} · ${run.environment} · Trigger: ${run.trigger}`} eyebrow={<><GitBranch className="h-3 w-3"/>Pipeline execution <StatusBadge status={run.status}/></>} action={<div className="flex gap-2"><Link href={`/pipelines/${run.pipelineId}`}><Button>View Pipeline</Button></Link><Link href={`/data-sources/${run.sourceId}`}><Button>View Source</Button></Link><Link href={`/logs?run=${encodeURIComponent(run.id)}`}><Button><FileText className="h-3.5 w-3.5"/> View Logs</Button></Link></div>}/>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Status" value={run.status} detail={run.platformCode} icon={Activity}/><MetricCard label="Started" value={formatTimestamp(run.startedAt)} detail="Exact API timestamp" icon={CalendarClock}/><MetricCard label="Finished" value={run.finishedAt?formatTimestamp(run.finishedAt):"In progress"} detail="Exact API timestamp" icon={CalendarClock}/><MetricCard label="Duration" value={run.duration} detail="Canonical duration" icon={Clock3}/><MetricCard label="Records" value={NOT_AVAILABLE} detail="Not supplied by this API" icon={Database}/></div>
 <div className="mt-7"><Card title="Operational Status" description="Execution outcome and authoritative technical identifiers."><div className="p-4"><OperationalStatus result={result}/><TechnicalDetails className="mt-4 border-t pt-4" items={[{label:"Platform Code",value:run.platformCode},{label:"Vendor Code",value:run.vendorCode??NOT_AVAILABLE},{label:"Rule Code",value:run.ruleCode??NOT_AVAILABLE},{label:"Airflow DAG ID",value:run.airflow.dag_id},{label:"Airflow Run ID",value:run.airflow.airflow_run_id},{label:"Source",value:run.sourceName}]}/></div></Card></div>
 <div className="mt-7"><Card title="Execution Stage" description="The stage reported by the canonical run resource.">{run.stages.length?<div className="p-4">{run.stages.map(stage=><div key={stage.name} className="rounded-lg border p-4 text-xs"><div className="flex items-center justify-between"><strong>{stage.name}</strong><StatusBadge status={stage.state}/></div><p className="mt-2 text-zinc-600">{stage.message??"No stage message available."}</p><TechnicalDetails className="mt-3" items={[{label:"Duration",value:stage.duration},{label:"Platform Code",value:stage.platformCode??NOT_AVAILABLE},{label:"Vendor Code",value:stage.vendorCode??NOT_AVAILABLE},{label:"Rule Code",value:stage.ruleCode??NOT_AVAILABLE}]}/></div>)}</div>:<div className="p-4"><EmptyState title="Stage not available" description="The backend did not return a current stage." icon={<Activity className="h-4 w-4"/>}/></div>}</Card></div>
 <div className="mt-7 grid gap-7 xl:grid-cols-2"><Card title="Validation" description="Validation executions returned with this run."><div className="p-4"><div className="grid grid-cols-3 gap-2">{[["Checks",run.validation.checks],["Passing",run.validation.passing],["Failed",run.validation.failed]].map(([label,value])=><div key={label} className="rounded bg-zinc-50 p-3"><p className="text-lg font-semibold">{value}</p><p className="text-[11px] text-zinc-500">{label}</p></div>)}</div><p className="mt-3 text-xs text-zinc-500">Evaluated: {run.validation.evaluatedAt?formatTimestamp(run.validation.evaluatedAt):NOT_AVAILABLE}</p>{run.validation.failure&&<div className="mt-4 rounded border border-rose-100 bg-rose-50/40 p-3 text-xs"><strong>{run.validation.failure.check}</strong><p className="mt-1">Field: {run.validation.failure.field} · Actual: {run.validation.failure.observed} · Expected: {run.validation.failure.threshold}</p><p className="mt-2 font-mono text-[10px]">{run.validation.platformCode}{run.validation.ruleCode?` · Rule: ${run.validation.ruleCode}`:""}{run.validation.vendorCode?` · Vendor: ${run.validation.vendorCode}`:""}</p></div>}<Link href={`/validation?run=${encodeURIComponent(run.id)}`}><Button className="mt-4"><FileCheck2 className="h-3.5 w-3.5"/> View Validation</Button></Link></div></Card><Card title="Related Alerts" description="Alerts associated with this canonical execution.">{run.alerts.length?<div className="space-y-3 p-4">{run.alerts.map(alert=><Link key={alert.alert_key} href={`/alerts/${alert.alert_key}`} className="block rounded border p-3 text-xs hover:bg-zinc-50"><div className="flex justify-between"><strong>{alert.title}</strong><StatusBadge status={alert.status}/></div><p className="mt-2 text-zinc-600">{alert.message}</p><p className="mt-2 font-mono text-[10px]">{alert.alert_key} · {alert.platform_code}{alert.rule_code?` · Rule: ${alert.rule_code}`:alert.vendor_code?` · Vendor: ${alert.vendor_code}`:""}</p></Link>)}</div>:<div className="p-4"><EmptyState title="No related alerts" description="No alerts were returned for this run." icon={<Activity className="h-4 w-4"/>}/></div>}</Card></div>
 <div className="mt-7"><Card title="Technical Evidence" description="Chronological technical events returned by the backend.">{run.events.length?<ol className="space-y-4 p-4">{run.events.map(event=><li key={event.id} className="border-l-2 border-zinc-200 pl-4 text-xs"><div className="flex justify-between gap-3"><strong>{event.title}</strong><time className="text-zinc-400">{formatTimestamp(event.timestamp)}</time></div><p className="mt-1 font-mono text-[10px] text-zinc-500">{event.code}</p></li>)}</ol>:<div className="p-4"><EmptyState title="No technical evidence" description="No technical events were returned for this run." icon={<Activity className="h-4 w-4"/>}/></div>}</Card></div>
 </div>
}
export function PipelineRunDetailSkeleton(){return <div className="space-y-7"><Skeleton className="h-20"/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{Array.from({length:5}).map((_,i)=><Skeleton key={i} className="h-28"/>)}</div><Skeleton className="h-72"/><Skeleton className="h-64"/></div>}
