"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Activity, CircleCheck, CircleX, Play, Search } from "lucide-react";
import type { PipelineRunListResponse } from "@/lib/api-contract";
import { environmentApiValue, enumApiValue, mapPipelineRun } from "@/lib/core-resource-adapters";
import { useApiQuery } from "@/lib/use-api-query";
import { useEnvironmentContext } from "@/lib/environment-context";
import { Button, EmptyState, ErrorState, FilterSelect, MetricCard, PageHeader, SearchField, Skeleton, StatusBadge } from "@/components/ui";

const LIMIT=20;
function iso(value:string){return value?new Date(value).toISOString():undefined}

export function PipelineRunsPage(){
 const router=useRouter();const params=useSearchParams();const{currentEnvironment}=useEnvironmentContext();
 const[query,setQuery]=useState(params.get("q")??"");const[status,setStatus]=useState(params.get("status")??"All");const[stage,setStage]=useState(params.get("stage")??"All");const[pipeline,setPipeline]=useState(params.get("pipeline")??"All");const[source,setSource]=useState(params.get("source")??"All");const[environment,setEnvironment]=useState(params.get("environment")??currentEnvironment);const[startedFrom,setStartedFrom]=useState(params.get("started_from")??"");const[startedTo,setStartedTo]=useState(params.get("started_to")??"");const[offset,setOffset]=useState(0);
 useEffect(()=>setOffset(0),[query,status,stage,pipeline,source,environment,startedFrom,startedTo]);
 const request=useApiQuery<PipelineRunListResponse>("/api/v1/pipeline-runs",{limit:LIMIT,offset,pipeline:pipeline==="All"?undefined:pipeline,environment:environmentApiValue(environment),status:enumApiValue(status),stage:enumApiValue(stage),source:source==="All"?undefined:source,started_from:iso(startedFrom),started_to:iso(startedTo),search:query.trim()||undefined},250);
 const runs=useMemo(()=>request.data?.items.map(mapPipelineRun)??[],[request.data]);const total=request.data?.pagination.total??0;const hasFilters=Boolean(query||status!=="All"||stage!=="All"||pipeline!=="All"||source!=="All"||environment!=="All"||startedFrom||startedTo);const clear=()=>{setQuery("");setStatus("All");setStage("All");setPipeline("All");setSource("All");setEnvironment(currentEnvironment);setStartedFrom("");setStartedTo("")};
 if(request.loading&&!request.data)return <PipelineRunsSkeleton/>;
 const successful=runs.filter((run)=>run.status==="Success").length;const failed=runs.filter((run)=>run.status==="Failed").length;const resolved=successful+failed;
 return <div className="animate-enter"><PageHeader title="Pipeline Runs" description="View and investigate pipeline execution history."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total Runs" value={String(total)} detail="Matching current filters" icon={Activity}/><MetricCard label="Running" value={String(runs.filter((run)=>run.status==="Running").length)} detail="On this page" icon={Play}/><MetricCard label="Failed" value={String(failed)} detail="On this page" icon={CircleX} tone="danger"/><MetricCard label="Success Rate" value={resolved?`${((successful/resolved)*100).toFixed(1)}%`:"Not available"} detail="On this page" icon={CircleCheck} tone="positive"/></div>
 <section className="mt-7"><div className="mb-3 flex flex-wrap gap-2"><SearchField value={query} onChange={setQuery} placeholder="Search runs..." className="w-full sm:max-w-xs"/><FilterSelect label="Pipeline" value={pipeline} onChange={setPipeline} options={[{label:"All pipelines",value:"All"},{label:"Events Processing",value:"events-processing"},{label:"Billing Reconciliation",value:"billing-reconciliation"},{label:"Customer Ingestion",value:"customer-ingestion"}]}/><FilterSelect label="Environment" value={environment} onChange={setEnvironment} options={["All","Production","Staging","Development"].map(value=>({label:value==="All"?"All environments":value,value}))}/><FilterSelect label="Status" value={status} onChange={setStatus} options={["All","Success","Failed","Running"].map(value=>({label:value==="All"?"All statuses":value,value}))}/><FilterSelect label="Stage" value={stage} onChange={setStage} options={["All","Extract","Transform","Validate","Load"].map(value=>({label:value==="All"?"All stages":value,value}))}/><FilterSelect label="Source" value={source} onChange={setSource} options={[{label:"All sources",value:"All"},{label:"Events Kafka",value:"events-kafka"},{label:"Billing PostgreSQL",value:"billing-postgres"},{label:"Production Warehouse",value:"production-warehouse"}]}/><label className="text-[10px] font-semibold uppercase text-zinc-400">Started from<input type="datetime-local" value={startedFrom} onChange={event=>setStartedFrom(event.target.value)} className="mt-1 block h-9 rounded-md border border-zinc-200 bg-white px-2 text-xs font-normal normal-case text-zinc-700"/></label><label className="text-[10px] font-semibold uppercase text-zinc-400">Started to<input type="datetime-local" value={startedTo} onChange={event=>setStartedTo(event.target.value)} className="mt-1 block h-9 rounded-md border border-zinc-200 bg-white px-2 text-xs font-normal normal-case text-zinc-700"/></label></div>
 {request.error?<ErrorState title={request.error.kind==="permission"?"Permission denied":"Pipeline runs couldn't be loaded"} description={request.error.message} actionLabel={request.error.retryable?"Try Again":undefined} onRetry={request.error.retryable?request.retry:undefined} technicalDetails={[{label:"Platform Code",value:request.error.code}]}/>:!runs.length?<EmptyState title={hasFilters?"No runs match your filters":"No pipeline runs available"} description={hasFilters?"Try adjusting the filters.":"No canonical pipeline runs were returned."} icon={<Search className="h-4 w-4"/>} action={hasFilters?<Button onClick={clear}>Clear filters</Button>:undefined}/>:<><div className="overflow-x-auto rounded-lg border border-zinc-200 bg-white shadow-card"><table className="w-full min-w-[1080px] text-left"><thead><tr className="border-b bg-zinc-50 text-[10px] uppercase tracking-wider text-zinc-400"><th className="px-4 py-2.5">Run</th><th className="px-3 py-2.5">Pipeline</th><th className="px-3 py-2.5">Source</th><th className="px-3 py-2.5">Status</th><th className="px-3 py-2.5">Stage</th><th className="px-3 py-2.5">Started</th><th className="px-3 py-2.5">Duration</th><th className="px-3 py-2.5">Technical codes</th></tr></thead><tbody>{runs.map(run=><tr key={run.id} tabIndex={0} onClick={()=>router.push(`/pipeline-runs/${run.id}`)} onKeyDown={event=>{if(event.key==="Enter")router.push(`/pipeline-runs/${run.id}`)}} className="cursor-pointer border-b text-xs last:border-0 hover:bg-zinc-50"><td className="px-4 py-3 font-mono text-[10px] font-medium text-zinc-800">{run.id}</td><td className="px-3 py-3"><span className="font-medium">{run.pipelineName}</span><span className="block font-mono text-[10px] text-zinc-400">{run.pipelineId}</span></td><td className="px-3 py-3">{run.sourceName}</td><td className="px-3 py-3"><StatusBadge status={run.status}/></td><td className="px-3 py-3">{run.stage}</td><td className="px-3 py-3">{run.startedDisplay}</td><td className="px-3 py-3">{run.duration}</td><td className="px-3 py-3 font-mono text-[10px]"><span className="block">{run.platformCode??"Not available"}</span>{run.vendorCode&&<span className="block text-zinc-500">Vendor: {run.vendorCode}</span>}{run.ruleCode&&<span className="block text-zinc-500">Rule: {run.ruleCode}</span>}</td></tr>)}</tbody></table></div><div className="mt-3 flex items-center justify-between text-xs text-zinc-500"><span>{request.data?.pagination.returned_count??0} shown · {total} total</span><div className="flex gap-2"><Button disabled={offset===0||request.loading} onClick={()=>setOffset(Math.max(0,offset-LIMIT))}>Previous</Button><Button disabled={offset+(request.data?.pagination.returned_count??0)>=total||request.loading} onClick={()=>setOffset(offset+LIMIT)}>Next</Button></div></div></>}
 </section></div>
}
export function PipelineRunsSkeleton(){return <div className="space-y-7"><Skeleton className="h-16"/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:4}).map((_,i)=><Skeleton key={i} className="h-28"/>)}</div><Skeleton className="h-96"/></div>}
