import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import type { DataSourceDetail, DataSourceListItem, PipelineDetail, PipelineListItem, PipelineRunDetail, PipelineRunListItem } from "../lib/api-contract.ts";
import { environmentApiValue, enumApiValue, mapDataSource, mapDataSourceDetail, mapPipeline, mapPipelineDetail, mapPipelineRun, mapPipelineRunDetail, NOT_AVAILABLE } from "../lib/core-resource-adapters.ts";

const environment = { environment_key: "production", name: "Production" };
const sourceSummary = { source_key: "events-kafka", name: "Events Kafka", source_type: "KAFKA" as const, operational_status: "DISCONNECTED" as const };
const pipelineSummary = { pipeline_key: "events-processing", name: "Events Processing", operational_status: "FAILED" as const };
const baseRun = { corvetra_run_id: "run_01J94EVT18", status: "FAILED" as const, stage: "EXTRACT" as const, started_at: "2026-08-10T14:40:00Z", completed_at: "2026-08-10T14:41:35Z", duration_seconds: 95, platform_code: "PIPELINE_EXECUTION_FAILED", vendor_code: "SASL_AUTHENTICATION_FAILED", rule_code: null };

function sourceItem(source_key:string,name:string,source_type:DataSourceListItem["source_type"],operational_status:DataSourceListItem["operational_status"]):DataSourceListItem{return{source_key,name,source_type,operational_status,environment,connected_pipeline_count:1,last_observed_at:"2026-08-10T14:41:35Z"}}
function pipelineItem(pipeline_key:string,name:string,operational_status:PipelineListItem["operational_status"],source:PipelineListItem["source"]=sourceSummary):PipelineListItem{return{pipeline_key,name,operational_status,environment,source,is_enabled:true,latest_run:baseRun,current_issue:null}}
function runItem(overrides:Partial<PipelineRunListItem>={}):PipelineRunListItem{return{...baseRun,pipeline:pipelineSummary,source:sourceSummary,environment,active_alert_count:1,...overrides}}

test("maps the four canonical sources with authoritative statuses",()=>{const views=[sourceItem("events-kafka","Events Kafka","KAFKA","DISCONNECTED"),sourceItem("billing-postgres","Billing PostgreSQL","POSTGRESQL","WARNING"),sourceItem("production-warehouse","Production Warehouse","SNOWFLAKE","HEALTHY"),sourceItem("legacy-sql-server","Legacy SQL Server","SQL_SERVER","DISABLED")].map(mapDataSource);assert.deepEqual(views.map(item=>[item.name,item.status]),[["Events Kafka","Disconnected"],["Billing PostgreSQL","Warning"],["Production Warehouse","Healthy"],["Legacy SQL Server","Disabled"]]);assert.deepEqual(views.map(item=>item.id),["events-kafka","billing-postgres","production-warehouse","legacy-sql-server"])});

test("maps source filters and detail without unsupported values",()=>{assert.equal(environmentApiValue("Production"),"production");assert.equal(enumApiValue("SQL Server"),"SQL_SERVER");const dto:DataSourceDetail={...sourceItem("events-kafka","Events Kafka","KAFKA","DISCONNECTED"),connected_pipelines:[{pipeline_key:"events-processing",name:"Events Processing",is_enabled:true,operational_status:"FAILED",latest_run:baseRun}],validation_summary:{total:0,passed:0,failed:0,not_evaluated:0,blocking_failed:0,warning_failed:0,last_evaluated_at:null},active_alert_count:1,recent_evidence:[{event_key:"evt-1",occurred_at:"2026-08-10T14:41:35Z",level:"ERROR",stage:"EXTRACT",platform_code:"PIPELINE_EXECUTION_FAILED",vendor_code:"SASL_AUTHENTICATION_FAILED",rule_code:null,message:"Authentication failed"}]};const view=mapDataSourceDetail(dto);assert.equal(view.owner,NOT_AVAILABLE);assert.equal(view.health.latency,NOT_AVAILABLE);assert.equal(view.connectedPipelines[0].id,"events-processing");assert.match(view.connectedPipelines[0].lastRun,/2026/)});

test("maps exactly three canonical pipelines and preserves backend health",()=>{const billingSource={source_key:"billing-postgres",name:"Billing PostgreSQL",source_type:"POSTGRESQL" as const,operational_status:"WARNING" as const};const warehouse={source_key:"production-warehouse",name:"Production Warehouse",source_type:"SNOWFLAKE" as const,operational_status:"HEALTHY" as const};const views=[pipelineItem("events-processing","Events Processing","FAILED"),pipelineItem("billing-reconciliation","Billing Reconciliation","WARNING",billingSource),pipelineItem("customer-ingestion","Customer Ingestion","HEALTHY",warehouse)].map(mapPipeline);assert.deepEqual(views.map(item=>[item.name,item.status]),[["Events Processing","Failed"],["Billing Reconciliation","Warning"],["Customer Ingestion","Healthy"]]);assert.ok(views.every(item=>item.schedule===NOT_AVAILABLE&&item.nextRun===NOT_AVAILABLE))});

test("pipeline detail uses latest/recent canonical runs and persisted configuration only",()=>{const dto={...pipelineItem("events-processing","Events Processing","FAILED"),airflow_dag_id:"corvetra_events",recent_runs:[baseRun],validation_summary:{total:0,passed:0,failed:0,not_evaluated:0,blocking_failed:0,warning_failed:0,last_evaluated_at:null},active_alerts:[],technical_evidence_count:2} as PipelineDetail;const view=mapPipelineDetail(dto);assert.equal(view.recentRuns[0].id,"run_01J94EVT18");assert.equal(view.destination.name,NOT_AVAILABLE);assert.ok(view.configuration.some(item=>item.value==="corvetra_events"));assert.equal(view.dependencies.length,0)});

test("maps exactly five canonical runs and never invents legacy identities",()=>{const ids=["run_01J94EVT18","run_01J97BIL02","run_01J92CING8","run_01J92CVAL9","run_01JA7OLD40"];const views=ids.map(id=>mapPipelineRun(runItem({corvetra_run_id:id})));assert.deepEqual(views.map(item=>item.id),ids);assert.equal(views.some(item=>item.id.includes("postgres")),false);assert.equal(views.find(item=>item.id==="run_01J94EVT18")?.stage,"Extract")});

test("Billing rule_code remains distinct from vendor_code in run detail",()=>{const billing={...runItem({corvetra_run_id:"run_01J97BIL02",pipeline:{pipeline_key:"billing-reconciliation",name:"Billing Reconciliation",operational_status:"WARNING"},source:{source_key:"billing-postgres",name:"Billing PostgreSQL",source_type:"POSTGRESQL",operational_status:"WARNING"},stage:"VALIDATE",platform_code:"VALIDATION_CHECK_FAILED",vendor_code:null,rule_code:"CHECK_UNIQUENESS_VIOLATION"}),airflow:{dag_id:"billing",airflow_run_id:"scheduled__billing"},alerts:[{alert_key:"ALT-1040",title:"Uniqueness failure",severity:"WARNING",status:"OPEN",platform_code:"VALIDATION_CHECK_FAILED",vendor_code:null,rule_code:"CHECK_UNIQUENESS_VIOLATION",message:"Duplicates",detected_at:"2026-08-10T14:00:00Z",last_seen_at:"2026-08-10T14:00:00Z",acknowledged_at:null,resolved_at:null}],validation_summary:{total:1,passed:0,failed:1,not_evaluated:0,blocking_failed:1,warning_failed:0,last_evaluated_at:"2026-08-10T14:00:00Z"},validation_executions:[{check_key:"order-id-unique",name:"Order ID unique",type:"UNIQUE",dataset_name:"orders",column_name:"order_id",result:"FAILED",severity:"BLOCKING",platform_code:"VALIDATION_CHECK_FAILED",rule_code:"CHECK_UNIQUENESS_VIOLATION",vendor_code:null,actual:"318",expected:"0",message:"Duplicates",evaluated_at:"2026-08-10T14:00:00Z"}],technical_evidence_count:0,technical_evidence:[]} as PipelineRunDetail;const view=mapPipelineRunDetail(billing);assert.equal(view.ruleCode,"CHECK_UNIQUENESS_VIOLATION");assert.equal(view.vendorCode,undefined);assert.equal(view.alerts[0].alert_key,"ALT-1040");assert.equal(view.validation.ruleCode,"CHECK_UNIQUENESS_VIOLATION")});

test("production routes are API-backed, direct-link safe, and do not import mock resources",async()=>{const root=fileURLToPath(new URL("..",import.meta.url));const files=["components/data-sources.tsx","components/data-source-detail.tsx","components/pipelines.tsx","components/pipeline-detail.tsx","components/pipeline-runs.tsx","components/pipeline-run-detail.tsx","app/data-sources/[sourceId]/page.tsx","app/pipelines/[pipelineId]/page.tsx","app/pipeline-runs/[runId]/page.tsx"];const text=(await Promise.all(files.map(file=>readFile(`${root}/${file}`,"utf8")))).join("\n");assert.doesNotMatch(text,/data-sources-data|pipelines-data|pipeline-runs-data|pipeline-run-detail-data|mock-run-state|generateStaticParams|dynamicParams\s*=\s*false|notFound\(/);assert.match(text,/\/api\/v1\/data-sources/);assert.match(text,/\/api\/v1\/pipelines/);assert.match(text,/\/api\/v1\/pipeline-runs/);assert.doesNotMatch(text,/run_01J92CING8/)});

test("request state cancels stale requests and ignores stale responses",async()=>{const root=fileURLToPath(new URL("..",import.meta.url));const hook=await readFile(`${root}/lib/use-api-query.ts`,"utf8");assert.match(hook,/AbortController/);assert.match(hook,/requestNumber/);assert.match(hook,/controller\.abort\(\)/);assert.match(hook,/kind === "cancelled"/)});
