import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import type { AlertListItem, LogEventListItem, ValidationExecutionDetail, ValidationListItem } from "../lib/api-contract.ts";
import { mapAlert, mapLogEvent, mapValidation, NOT_AVAILABLE } from "../lib/core-resource-adapters.ts";

const environment={environment_key:"production",name:"Production"};
const eventSource={source_key:"events-kafka",name:"Events Kafka",source_type:"KAFKA" as const,operational_status:"DISCONNECTED" as const};
const eventPipeline={pipeline_key:"events-processing",name:"Events Processing",operational_status:"FAILED" as const};
const eventRun={corvetra_run_id:"run_01J94EVT18",status:"FAILED" as const,stage:"EXTRACT" as const,started_at:"2026-08-10T14:40:00Z",completed_at:"2026-08-10T14:41:35Z",duration_seconds:95,platform_code:"PIPELINE_EXECUTION_FAILED",vendor_code:"SASL_AUTHENTICATION_FAILED",rule_code:null};
function alert(id:string,overrides:Partial<AlertListItem>={}):AlertListItem{return{alert_key:id,title:id==="ALT-1042"?"Events failure":"Billing validation failure",severity:id==="ALT-1042"?"CRITICAL":"WARNING",status:"OPEN",platform_code:id==="ALT-1042"?"PIPELINE_EXECUTION_FAILED":"VALIDATION_CHECK_FAILED",vendor_code:id==="ALT-1042"?"SASL_AUTHENTICATION_FAILED":null,rule_code:id==="ALT-1040"?"CHECK_UNIQUENESS_VIOLATION":null,message:"Canonical alert",detected_at:"2026-08-10T14:41:35Z",last_seen_at:"2026-08-10T14:41:35Z",acknowledged_at:null,resolved_at:null,pipeline:eventPipeline,run:eventRun,source:eventSource,environment,validation_execution:null,...overrides}}

test("maps canonical ALT-1042 and ALT-1040 with authoritative cross-links",()=>{const views=[mapAlert(alert("ALT-1042")),mapAlert(alert("ALT-1040",{pipeline:{pipeline_key:"billing-reconciliation",name:"Billing Reconciliation",operational_status:"WARNING"},run:{...eventRun,corvetra_run_id:"run_01J97BIL02",stage:"VALIDATE",platform_code:"VALIDATION_CHECK_FAILED",vendor_code:null,rule_code:"CHECK_UNIQUENESS_VIOLATION"},source:{source_key:"billing-postgres",name:"Billing PostgreSQL",source_type:"POSTGRESQL",operational_status:"WARNING"}}))];assert.deepEqual(views.map(view=>view.id),["ALT-1042","ALT-1040"]);assert.equal(views[0].runId,"run_01J94EVT18");assert.equal(views[0].sourceId,"events-kafka");assert.equal(views[1].runId,"run_01J97BIL02");assert.equal(views[1].ruleCode,"CHECK_UNIQUENESS_VIOLATION");assert.equal(views[1].vendorCode,null)});

const billingValidation:ValidationListItem={check_key:"order-id-unique",name:"Order ID unique",type:"UNIQUE",dataset_name:"orders",column_name:"order_id",result:"FAILED",severity:"BLOCKING",platform_code:"VALIDATION_CHECK_FAILED",rule_code:"CHECK_UNIQUENESS_VIOLATION",vendor_code:null,actual:"318 duplicates",expected:"0 duplicates",message:"Duplicate order IDs",evaluated_at:"2026-08-10T14:38:42Z",stage:"VALIDATE",run:{...eventRun,corvetra_run_id:"run_01J97BIL02",stage:"VALIDATE",platform_code:"VALIDATION_CHECK_FAILED",vendor_code:null,rule_code:"CHECK_UNIQUENESS_VIOLATION"},pipeline:{pipeline_key:"billing-reconciliation",name:"Billing Reconciliation",operational_status:"WARNING"},source:{source_key:"billing-postgres",name:"Billing PostgreSQL",source_type:"POSTGRESQL",operational_status:"WARNING"},environment};
test("preserves validation check definition versus execution identity",()=>{const view=mapValidation(billingValidation);assert.equal(view.checkKey,"order-id-unique");assert.equal(view.runId,"run_01J97BIL02");assert.equal(view.checkType,"Unique");assert.equal(view.result,"Failed");assert.equal(view.stage,"Validate")});
test("Billing uniqueness violation is only a rule code",()=>{const view=mapValidation(billingValidation);assert.equal(view.platformCode,"VALIDATION_CHECK_FAILED");assert.equal(view.ruleCode,"CHECK_UNIQUENESS_VIOLATION");assert.equal(view.vendorCode,null)});
test("validation detail preserves ALT-1040 and technical evidence links",()=>{const detail={...billingValidation,related_alerts:[{alert_key:"ALT-1040",title:"Billing validation failure",severity:"WARNING",status:"OPEN",platform_code:"VALIDATION_CHECK_FAILED",vendor_code:null,rule_code:"CHECK_UNIQUENESS_VIOLATION",message:"Duplicates",detected_at:"2026-08-10T14:38:42Z",last_seen_at:"2026-08-10T14:38:42Z",acknowledged_at:null,resolved_at:null}],technical_evidence_count:1,technical_evidence:[{event_key:"evt-007",occurred_at:"2026-08-10T14:38:42Z",level:"ERROR",stage:"VALIDATE",platform_code:"VALIDATION_CHECK_FAILED",vendor_code:null,rule_code:"CHECK_UNIQUENESS_VIOLATION",message:"Uniqueness check failed"}],recent_executions:[]} as ValidationExecutionDetail;assert.equal(detail.related_alerts[0].alert_key,"ALT-1040");assert.equal(detail.technical_evidence[0].event_key,"evt-007")});

function logEvent(overrides:Partial<LogEventListItem>={}):LogEventListItem{return{event_key:"evt-005",occurred_at:"2026-08-10T14:41:35Z",level:"ERROR",message:"Kafka authentication failed",environment,pipeline:eventPipeline,run:eventRun,source:eventSource,stage:"EXTRACT",platform_code:"PIPELINE_EXECUTION_FAILED",vendor_code:"SASL_AUTHENTICATION_FAILED",rule_code:null,related_alert:{alert_key:"ALT-1042",status:"OPEN"},related_validation:null,...overrides}}
test("maps real Events and Billing evidence without collapsing technical codes",()=>{const events=mapLogEvent(logEvent());assert.equal(events.id,"evt-005");assert.equal(events.alertId,"ALT-1042");assert.equal(events.runId,"run_01J94EVT18");assert.equal(events.vendorCode,"SASL_AUTHENTICATION_FAILED");assert.equal(events.ruleCode,null);const billing=mapLogEvent(logEvent({event_key:"evt-007",vendor_code:null,rule_code:"CHECK_UNIQUENESS_VIOLATION",related_alert:{alert_key:"ALT-1040",status:"OPEN"},related_validation:{check_key:"order-id-unique",name:"Order ID unique",result:"FAILED",severity:"BLOCKING",evaluated_at:"2026-08-10T14:38:42Z"}}));assert.equal(billing.vendorCode,null);assert.equal(billing.ruleCode,"CHECK_UNIQUENESS_VIOLATION");assert.equal(billing.validationCheckKey,"order-id-unique")});
test("null log resource relationships remain unavailable rather than fabricated",()=>{const view=mapLogEvent(logEvent({pipeline:null,run:null,source:null,stage:null,platform_code:null,vendor_code:null}));assert.equal(view.pipelineId,null);assert.equal(view.runId,null);assert.equal(view.sourceId,null);assert.equal(view.stage,null);assert.equal(view.platformCode,null);assert.equal(NOT_AVAILABLE,"Not available")});

test("Step 3 production paths are API-backed, direct-link safe, and mutation-free",async()=>{const root=fileURLToPath(new URL("..",import.meta.url));const files=["components/alerts.tsx","components/alert-detail.tsx","components/validation.tsx","components/validation-detail.tsx","components/logs.tsx","app/alerts/[alertId]/page.tsx","app/validation/[validationId]/page.tsx"];const contents=await Promise.all(files.map(file=>readFile(`${root}/${file}`,"utf8")));const text=contents.join("\n");assert.doesNotMatch(text,/alerts-data|validation-data|logs-data|persistAlert|DEMO_NOW|mockNow|generateStaticParams|notFound\(|run_01J92CING8/);assert.match(text,/\/api\/v1\/alerts/);assert.match(text,/\/api\/v1\/validation/);assert.match(text,/\/api\/v1\/logs/);assert.match(contents[1],/disabled title="Alert acknowledgement is not supported/);assert.doesNotMatch(text,/setInterval|auto-refresh/i)});
test("Step 3 screens expose backend filters and pagination metadata",async()=>{const root=fileURLToPath(new URL("..",import.meta.url));const text=(await Promise.all(["components/alerts.tsx","components/validation.tsx","components/logs.tsx"].map(file=>readFile(`${root}/${file}`,"utf8")))).join("\n");for(const field of ["returned_count","offset","search","platform_code","rule_code"]){assert.match(text,new RegExp(field))}assert.match(text,/activity_from/);assert.match(text,/evaluated_from/);assert.match(text,/occurred_from/)});
